# Generated by Django 2.0.7 on 2018-08-06 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('renew_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '好友',
                'db_table': 'mbr_friendship',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='會員代號')),
                ('account', models.EmailField(help_text='你的電子信箱', max_length=50, unique=True, verbose_name='帳號')),
                ('identifier', models.CharField(max_length=22, verbose_name='會員識別碼')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='暱稱')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='密碼')),
                ('localpicture', models.ImageField(blank=True, max_length=64, null=True, upload_to='', verbose_name='本機照片')),
                ('dbpicture', models.ImageField(blank=True, max_length=64, null=True, upload_to='', verbose_name='資料庫照片')),
                ('renew_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
                ('friendship', models.ManyToManyField(through='api.FriendShip', to='api.Member')),
            ],
            options={
                'db_table': 'mbr_member',
            },
        ),
        migrations.CreateModel(
            name='Membertype',
            fields=[
                ('membertype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='member', max_length=10)),
                ('renew_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'sys_membertype',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membertype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Membertype'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_id',
            field=models.ForeignKey(db_column='friend_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_friend_id', to='api.Member', verbose_name='好友代號'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_member_id', to='api.Member', verbose_name='會員代號'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('member_id', 'friend_id')},
        ),
    ]
