# Generated by Django 2.0.7 on 2018-07-22 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='會員代號')),
                ('account', models.EmailField(help_text='你的電子信箱', max_length=50, unique=True, verbose_name='帳號')),
                ('identifier', models.CharField(max_length=22, verbose_name='會員識別碼')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='暱稱')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='密碼')),
                ('localpicture', models.ImageField(blank=True, max_length=64, null=True, upload_to='', verbose_name='本機照片')),
                ('dbpicture', models.ImageField(blank=True, max_length=64, null=True, upload_to='', verbose_name='資料庫照片')),
                ('renew_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'mbr_member',
            },
        ),
        migrations.CreateModel(
            name='Membertype',
            fields=[
                ('membertype_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='會員類型代號')),
                ('name', models.CharField(max_length=10, verbose_name='類型名稱')),
                ('renew_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '會員類型',
                'verbose_name_plural': '會員類型',
                'db_table': 'sys_membertype',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Membertype'),
        ),
    ]
