# Generated by Django 2.0.7 on 2018-07-23 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180723_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertype',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='renew_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間'),
        ),
    ]
