# Generated by Django 2.0.7 on 2018-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180723_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dbpicture',
            field=models.FilePathField(blank=True, max_length=64, null=True, verbose_name='資料庫照片'),
        ),
        migrations.AlterField(
            model_name='member',
            name='localpicture',
            field=models.FilePathField(blank=True, max_length=64, null=True, verbose_name='本機照片'),
        ),
    ]
