# Generated by Django 2.0.7 on 2018-07-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180723_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membertype',
            new_name='membertype_id',
        ),
    ]
