# Generated by Django 2.0.7 on 2018-07-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180725_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membertype_id',
            new_name='membertype',
        ),
    ]
